### ISSUE TITLE
no ckpt.npz

### ISSUE THREAD

**Issue by HeChengy** [dvlab-research/Ref-NPR#10]
Hi,thanks your amazing work.There is a problem.
No such file or directory:'./exps/base_pr/ckpt_svox2/llff/flower/ckpt.npz
Can you share your ckpt.npz?Thanks a lot.

**Comment by JulianJuaner** [comment]
Hi, 
The checkpoiint file should exist if you follow the instructions in README.md normally.
I also share my optimized checkpoint at https://mycuhk-my.sharepoint.com/:f:/g/personal/1155091988_link_cuhk_edu_hk/EsHkKoZjUz5LiOeUYujHYegBsca0V8o5jm37mZ_AUBvETA?e=zYYG3B

**Comment by JulianJuaner** [comment]
@HeChengy Also, please refer to #6 if you have encountered the same problem.
