### ISSUE TITLE
An issue about svox2

### ISSUE THREAD

**Issue by ziye5731** [dvlab-research/Ref-NPR#11]
Great work! I currently have trouble with the code. When I run the code (at step 2 and step 3), there is always a traceback:
Traceback (most recent call last):
  File "opt.py", line 471, in <module>
    eval_step()
  File "opt.py", line 406, in eval_step
    rgb_pred_test = grid.volume_render_image(cam, use_kernel=True)
  File "....../anaconda3/envs/RefNPR/lib/python3.8/site-packages/svox2/svox2.py", line 1210, in volume_render_image
    and imrend_fn_name in _C.__dict__
AttributeError: 'NoneType' object has no attribute '__dict__'
How can I solve the issue, is there a problem when creating the environment? Thank you so much!

**Comment by ronly2460** [comment]
Svox should be built on GPU.
You can check it by setting -v option inpip install. If it fails, there's warnings regarding cuda or gpu. Additionally, make sure that torch.cuda.is_available is True.

**Comment by ziye5731** [comment]
There is a warning regarding cuda extension when installing svox2 and import it. I will check it at Plenoxels webpage. Thanks!
