### ISSUE TITLE
A problem in ref_regist.py file

### ISSUE THREAD

**Issue by ziye5731** [dvlab-research/Ref-NPR#13]
When I was training the ref-npr model, I met such a traceback:

Traceback (most recent call last):
  File "./exps/refnpr/ref_regist.py", line 145, in <module>
    xyz_min = torch.minimum(xyz_min, torch.min(xyz_pos[depth_rep!=0].reshape(-1, 3), dim=0)[0])
IndexError: min(): Expected reduction dim 0 to have non-zero size.

It seems that for some dataset, during the iteration, `depth_rep` can be all 0 and `xyz_pos[depth_rep]` can therefore be `torch.tensor([])`.
How can I sovle the issue, can I firstly check `torch.any(depth_rep)` to deside whether running the following codes? Like:
```
if torch.any(depth_rep):
        xyz_min = torch.minimum(xyz_min, torch.min(xyz_pos[depth_rep!=0].reshape(-1, 3), dim=0)[0])
        xyz_max = torch.maximum(xyz_max, torch.max(xyz_pos[depth_rep!=0].reshape(-1, 3), dim=0)[0])
else:
        pass
```
Besides, `xyz_min` and `xyz_max` seems to stay stationary before the error occurs.

**Comment by JulianJuaner** [comment]
Sorry for the late reply
Weirdly, all depth_rep are zeros for one camera pose; I suggest you check your pre-trained field. 
Besides, your solution seems okay to solve this issue.

**Comment by ziye5731** [comment]
> Sorry for the late reply Weirdly, all depth_rep are zeros for one camera pose; I suggest you check your pre-trained field. Besides, your solution seems okay to solve this issue.

Thanks for reply. I think it's probably due to the pre-trained plenoxel. I remake my dataset and the problem seems to be solved.
