### ISSUE TITLE
when use svox2   Segmentation fault

### ISSUE THREAD

**Issue by jiennyteng** [dvlab-research/Ref-NPR#5]
hello, when I run the step 2,
meet the error Segmentation fault 
<img width="924" alt="image" src="https://github.com/dvlab-research/Ref-NPR/assets/116726469/64d0fe04-b191-40cb-b587-6a776533fa23">
and here is the svox2 implement 
<img width="924" alt="image" src="https://github.com/dvlab-research/Ref-NPR/assets/116726469/078d8c2f-7994-4944-aae5-c6990d172aa4">
and the torch enviroment
<img width="924" alt="image" src="https://github.com/dvlab-research/Ref-NPR/assets/116726469/c8680d55-2797-4e60-81d2-170b32387ef2">

**Comment by JulianJuaner** [comment]
You can follow the instructions for svox2 installation and environment settings https://github.com/sxyu/svox2/blob/master/environment.yml https://github.com/sxyu/svox2/tree/master. I will also update the requirement file later.
