### ISSUE TITLE
No such file or directory: './exps/refnpr/flower_colorful/exp_out/ckpt.npz/ckpt.npz'

### ISSUE THREAD

**Issue by Ysz2022** [dvlab-research/Ref-NPR#6]
I have successfully run Step 1 and 2. But when I run Step 3:bash ./exps/refnpr/run_single.sh ./data/ref_case/flower_colorful/, I meet the error that: "FileNotFoundError: [Errno 2] No such file or directory: './exps/refnpr/flower_colorful/exp_out/ckpt.npz/ckpt.npz'.

I found that in Step 2, I have got the file "./exps/base_pr/ckpt_svox2/llff/flower/ckpt.npz"
BUT in Sep 3, I need the file './exps/refnpr/flower_colorful/exp_out/ckpt.npz/ckpt.npz', which is not generated before.

**Comment by JulianJuaner** [comment]
> I have successfully run Step 1 and 2. But when I run Step 3:bash ./exps/refnpr/run_single.sh ./data/ref_case/flower_colorful/, I meet the error that: "FileNotFoundError: [Errno 2] No such file or directory: './exps/refnpr/flower_colorful/exp_out/ckpt.npz/ckpt.npz'.
> 
> I found that in Step 2, I have got the file "./exps/base_pr/ckpt_svox2/llff/flower/ckpt.npz" BUT in Sep 3, I need the file './exps/refnpr/flower_colorful/exp_out/ckpt.npz/ckpt.npz', which is not generated before.

Hi, can you provide your log info when running step 3? The run_single.sh has multiple steps. The rendering step needs the optimized checkpoint ( './exps/refnpr/flower_colorful/exp_out/ckpt.npz/ckpt.npz'). It seems the optimization step has some errors and unable to store the checkpoint file.

<img width="992" alt="Screenshot 2023-07-01 at 11 09 20 AM" src="https://github.com/dvlab-research/Ref-NPR/assets/37148692/40a8f2b5-8d29-40e3-834a-89efacbc3f08">

**Comment by Ysz2022** [comment]
I have no optimized checkpoint in my fold. If possible, please tell me the optimization command. Thank you very much !!!!!!!!!

**Comment by JulianJuaner** [comment]
> I have no optimized checkpoint in my fold. If possible, please tell me the optimization command. Thank you very much !!!!!!!!!

Hi, usually, if you run the run_single.sh in step 3, it will automatically run the optimization step at
https://github.com/dvlab-research/Ref-NPR/blob/main/exps/refnpr/run_single.sh#L13

If you still have problems finding the optimization checkpoint, I will check the whole pipeline tonight.

**Comment by Ysz2022** [comment]
Thanks for your kind response!!!! I have got it.
Additionally, I found that ARF developed their method based on plenoxels, NeRF and TensoRF. Ref-NPR seems to be based on plenoxels. That is because plenoxels is easy to train. I wonder Instant-NGP performs faster convergence speed, if it possible that apply artistic rendering to Instant-NGP is able to result in faster speed?

**Comment by JulianJuaner** [comment]
Yes, as a conceptual method, our approach can also perform well on other representations. I believe it is possible to apply rendering to Instant-NGP for faster optimization speed. If I have time, I will try to implement it! 😊
BTW, I will temporally close this issue, you are welcome to reopen it if you have any further questions!
