### ISSUE TITLE
Failed building wheel for svox2

### ISSUE THREAD

**Issue by HaibaraAi6** [dvlab-research/Ref-NPR#7]
Importing svox2 package under RefNPR environment will report the following error. But I can import svox2 package under base environment.
![image](https://github.com/dvlab-research/Ref-NPR/assets/138961893/e3318c55-e90d-4a93-afce-bbcff38b9041)

**Comment by JulianJuaner** [comment]
Could you please provide more information, like GPU/CUDA version? It seems the cuda is not found. You may try to set the CUDA_HOME to the correct directory manually.

**Comment by HaibaraAi6** [comment]
Thanks for your reply, now I successfully ran your script to run through the sample. But it is very difficult to debug the project without the script. Is there a more detailed running guide here please?

**Comment by JulianJuaner** [comment]
I'm sorry for not getting back to you sooner. Once you have set up the CUDA environment, following the instructions in the README file is the simplest way to reproduce results. We'll be sure to add detailed instructions later if you mean adding some guidance instructions in each running script. Thank you for your suggestions.

**Comment by HaibaraAi6** [comment]
Thank you very much, and I realized that the final outputs are  rendered 2D images. How can I get a rendered 3D radiation field like mentioned in the article?

**Comment by JulianJuaner** [comment]
It seems the rendered videos are already put into the result folder. [code link](https://github.com/dvlab-research/Ref-NPR/blob/main/exps/refnpr/run_single.sh#L19C1-L23C1)

`python -W ignore ./exps/ref_render.py ${OUTDIR} ${STYLE}\
                 --render_path`

In the ref_render.py, by default, the video will be rendered in the output folder) [code link](https://github.com/dvlab-research/Ref-NPR/blob/main/exps/ref_render.py#L194C1-L194C1)

<img width="1025" alt="Screenshot 2023-07-30 at 5 46 22 PM" src="https://github.com/dvlab-research/Ref-NPR/assets/37148692/312fbb1d-f390-4e0c-95ec-76d8db266fdd">

You may check your arguments [here](https://github.com/dvlab-research/Ref-NPR/blob/main/exps/arguments.py#L4C1-L5C9). (related arguments: --no_vid and --timing, you are not required to modify them if you just run the script run_single.sh)

<img width="981" alt="Screenshot 2023-07-30 at 5 48 24 PM" src="https://github.com/dvlab-research/Ref-NPR/assets/37148692/9e7f1d4f-260b-41a1-91d2-136ed5e57540">

**Comment by JulianJuaner** [comment]
I will temporally close this issue, you are welcome to reopen it if you have any further questions!
