### ISSUE TITLE
Ray Registration

### ISSUE THREAD

**Issue by HarukiYqM** [dvlab-research/Ref-NPR#8]
Hi author,

Thanks for posting the work. I have quick question about ray registration. From Line 227, it seems that the dictionary is a tensor that can only store a single ray. In case of multiple rays falling into a single grid, the grid will be overwritten by the latest ray.
Is that correct? 
https://github.com/dvlab-research/Ref-NPR/blob/b738f3dd0e21ae5718c46f88d02be48e8bcfcbc1/exps/refnpr/ref_regist.py#L227

**Comment by JulianJuaner** [comment]
You are right; we only sample one color in this implementation here as the projected rays are sparse in the 3D. A more direct way is to direct apply a depth-conditioned image warping on other training views with constraints described in the paper.

**Comment by HarukiYqM** [comment]
Thanks.
